version: '3.5'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    networks:
      - webproxy
    ports:
      - "80:80"
    volumes:
      - "./vhost.d:/etc/nginx/vhost.d"
      - ./conf.d/my_conf.conf:/etc/nginx/conf.d/my_conf.conf
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

networks:
    webproxy:
        external:
            name: webproxy
